Markdown ALL the things
zmike/vkoverhead pull request #24
Opened 2023-09-25 06:46 UTC by qwertychouskie

Closes https://github.com/zmike/vkoverhead/issues/23

2023-09-25 12:37 UTC, zmike commented
Thanks.

This is nice, but I'd rather have it as a non-default cmdline option (maybe `-m`) since generating markdown output isn't the primary use case. It should be pretty simple to rework it into a conditional.

2023-09-25 15:09 UTC, qwertychouskie commented
> Thanks.
> 
> This is nice, but I'd rather have it as a non-default cmdline option (maybe `-m`) since generating markdown output isn't the primary use case. It should be pretty simple to rework it into a conditional.

![image](https://github.com/zmike/vkoverhead/assets/13989090/0822793c-6f04-40f4-b201-c5b01fa39956)

![image](https://github.com/zmike/vkoverhead/assets/13989090/cb37a115-529c-426e-8fcd-436eb8753d5a)

Call me crazy, but I think the Markdown is much more readable as terminal output as well.  (Also the old output was kinda broken in weird ways, like alignment was very inconsistent.)

2023-09-25 16:28 UTC, zmike commented
![image](https://github.com/zmike/vkoverhead/assets/234706/05971caa-4035-4dcb-9d32-4f92824943e6)

I'd be okay with `-csv` becoming the current output and markdown becoming the new default I suppose, so long as it's listed in `-help`.

2023-09-26 00:43 UTC, qwertychouskie commented
aight should be ready for review/merge i think
```
qwerty@qwerty-asus-g14:~/Projects/vkoverhead/builddir$ ./vkoverhead -help
vkoverhead [-list] [-test/start TESTNUM] [-duration SECONDS] [-nocolor] [-output-only] [-draw-only] [-submit-only] [-descriptor-only] [-misc-only] [-fixed ITERATIONS] [-csv]
qwerty@qwerty-asus-g14:~/Projects/vkoverhead/builddir$ ./vkoverhead

| Device Name                        | Driver Name | Driver Info |
| ---------------------------------- | ----------- | ----------- |
| NVIDIA GeForce RTX 3060 Laptop GPU | NVIDIA      | 535.86.05   |


|   # | Draw Tests                                          |    Kop/s | % relative to 'draw' |
| --: | --------------------------------------------------- | -------: | -----: |
|   0 | draw                                                |    52580 | 100.0% |
|   1 | draw_multi                                          |   224537 | 427.0% |
|   2 | draw_vertex                                         |    54139 | 103.0% |
|   3 | draw_multi_vertex                                   |   232658 | 442.5% |
|   4 | draw_index_change                                   |    39594 |  75.3% |
|   5 | draw_index_offset_change                            |    39961 |  76.0% |
|   6 | draw_rp_begin_end                                   |     1509 |   2.9% |
|   7 | draw_rp_begin_end_dynrender                         |     1065 |   2.0% |
|   8 | draw_rp_begin_end_dontcare                          |     1918 |   3.6% |
|   9 | draw_rp_begin_end_dontcare_dynrender                |     1220 |   2.3% |
|  10 | draw_multirt                                        |    52461 |  99.8% |
|  11 | draw_multirt_dynrender                              |    52375 |  99.6% |
|  12 | draw_multirt_begin_end                              |      495 |   0.9% |
|  13 | draw_multirt_begin_end_dynrender                    |      420 |   0.8% |
|  14 | draw_multirt_begin_end_dontcare                     |      746 |   1.4% |
|  15 | draw_multirt_begin_end_dontcare_dynrender           |      665 |   1.3% |
|  16 | draw_vbo_change                                     |    38087 |  72.4% |
|  17 | draw_1vattrib_change                                |     8885 |  16.9% |
|  18 | draw_16vattrib                                      |    52086 |  99.1% |
|  19 | draw_16vattrib_16vbo_change                         |     9256 |  17.6% |
|  20 | draw_16vattrib_change                               |     8509 |  16.2% |
|  21 | draw_16vattrib_change_dynamic                       |     9413 |  17.9% |
|  22 | draw_16vattrib_change_gpl                           |      317 |   0.6% |
|  23 | draw_16vattrib_change_gpl_hashncache                |     4359 |   8.3% |
|  24 | draw_1ubo_change                                    |    22145 |  42.1% |
|  25 | draw_12ubo_change                                   |     7440 |  14.2% |
|  26 | draw_1combined_sampler_change                       |    10132 |  19.3% |
|  27 | draw_16combined_sampler_change                      |     9698 |  18.4% |
|  28 | draw_1texelbuffer_change                            |    21260 |  40.4% |
|  29 | draw_16texelbuffer_change                           |    20224 |  38.5% |
|  30 | draw_1ssbo_change                                   |    21805 |  41.5% |
|  31 | draw_8ssbo_change                                   |    17861 |  34.0% |
|  32 | draw_1image_change                                  |    10165 |  19.3% |
|  33 | draw_16image_change                                 |     9975 |  19.0% |
|  34 | draw_1imagebuffer_change                            |    22095 |  42.0% |
|  35 | draw_16imagebuffer_change                           |    21372 |  40.6% |
|  36 | draw_ubo_db_change                                  |     4543 |   8.6% |
|  37 | draw_ssbo_db_change                                 |    30434 |  57.9% |
|  38 | draw_combined_sampler_db_change                     |    29287 |  55.7% |
|  39 | draw_image_db_change                                |    30436 |  57.9% |

|   # | Submit Tests                                        |     op/s | % relative to 'submit_noop |
| --: | --------------------------------------------------- | -------: | -----: |
|  40 | submit_noop                                         | 18681392 | 100.0% |
|  41 | submit_50noop                                       |  5423573 |  29.0% |
|  42 | submit_1cmdbuf                                      |   181525 |   1.0% |
|  43 | submit_50cmdbuf                                     |    12110 |   0.1% |
|  44 | submit_50cmdbuf_50submit                            |    12148 |   0.1% |

|   # | Descriptor Tests                                    |    Kop/s | % relative to 'descriptor_noop' |
| --: | --------------------------------------------------- | -------: | -----: |
|  45 | descriptor_noop                                     |   438907 | 100.0% |
|  46 | descriptor_1ubo                                     |   113762 |  25.9% |
|  47 | descriptor_template_1ubo                            |   106848 |  24.3% |
|  48 | descriptor_template_1ubo_push                       |    86077 |  19.6% |
|  49 | descriptor_12ubo                                    |    23098 |   5.3% |
|  50 | descriptor_template_12ubo                           |    22029 |   5.0% |
|  51 | descriptor_template_12ubo_push                      |    13501 |   3.1% |
|  52 | descriptor_1combined_sampler                        |   127263 |  29.0% |
|  53 | descriptor_template_1combined_sampler               |   116402 |  26.5% |
|  54 | descriptor_template_1combined_sampler_push          |    97005 |  22.1% |
|  55 | descriptor_16combined_sampler                       |    28018 |   6.4% |
|  56 | descriptor_template_16combined_sampler              |    27023 |   6.2% |
|  57 | descriptor_template_16combined_sampler_push         |    12924 |   2.9% |
|  58 | descriptor_1sampled_image                           |   134711 |  30.7% |
|  59 | descriptor_template_1sampled_image                  |   130673 |  29.8% |
|  60 | descriptor_template_1sampled_image_push             |    99137 |  22.6% |
|  61 | descriptor_16sampled_image                          |    31057 |   7.1% |
|  62 | descriptor_template_16sampled_image                 |    30348 |   6.9% |
|  63 | descriptor_template_16sampled_image_push            |    13079 |   3.0% |
|  64 | descriptor_1texelbuffer                             |   173208 |  39.5% |
|  65 | descriptor_template_1texelbuffer                    |   150157 |  34.2% |
|  66 | descriptor_template_1texelbuffer_push               |   100503 |  22.9% |
|  67 | descriptor_16texelbuffer                            |    39976 |   9.1% |
|  68 | descriptor_template_16texelbuffer                   |    39604 |   9.0% |
|  69 | descriptor_template_16texelbuffer_push              |    13742 |   3.1% |
|  70 | descriptor_1ssbo                                    |   132602 |  30.2% |
|  71 | descriptor_template_1ssbo                           |   126774 |  28.9% |
|  72 | descriptor_template_1ssbo_push                      |    94407 |  21.5% |
|  73 | descriptor_8ssbo                                    |    40430 |   9.2% |
|  74 | descriptor_template_8ssbo                           |    41819 |   9.5% |
|  75 | descriptor_template_8ssbo_push                      |    21133 |   4.8% |
|  76 | descriptor_1image                                   |   130809 |  29.8% |
|  77 | descriptor_template_1image                          |   128091 |  29.2% |
|  78 | descriptor_template_1image_push                     |    98116 |  22.4% |
|  79 | descriptor_16image                                  |    51945 |  11.8% |
|  80 | descriptor_template_16image                         |    49304 |  11.2% |
|  81 | descriptor_template_16image_push                    |    25519 |   5.8% |
|  82 | descriptor_1imagebuffer                             |   167387 |  38.1% |
|  83 | descriptor_template_1imagebuffer                    |   151570 [...]

2023-09-26 00:58 UTC, zmike requested changes

2023-09-26 00:58 UTC, zmike commented on src/common.c
> +void print_table_header(bool csv, char* column_1, char* column_2, char* column_3, char* column_4)
newline between return type and function name, move all this to vkoverhead.c

2023-09-26 00:58 UTC, zmike commented on src/vkoverhead.c
> +      print_table_header(csv, "#", "Draw Tests", "Kop/s", "% relative to 'draw'");
Use `1000op/s` since K isn't immediately clear in this context

2023-09-26 00:58 UTC, zmike commented on src/vkoverhead.c
> +  printf("\n");
indentation

2023-09-26 01:46 UTC, qwertychouskie commented on src/common.c
> +void print_table_header(bool csv, char* column_1, char* column_2, char* column_3, char* column_4)
Where in `vkoverhead.c` should the functions go?  The file is quite long and has a lot of stuff going on, thus my initial decision to put the functions in a separate file.

2023-09-26 01:49 UTC, zmike commented on src/common.c
> +void print_table_header(bool csv, char* column_1, char* column_2, char* column_3, char* column_4)
just jam em in above `perf_run`. common.c is code copied from piglit

2023-09-26 02:14 UTC, qwertychouskie commented on src/common.c
> +void print_table_header(bool csv, char* column_1, char* column_2, char* column_3, char* column_4)
Fixed

~~also what kind of monster uses 3 spaces for indentation~~

2023-09-26 02:24 UTC, zmike commented on src/common.c
> +void print_table_header(bool csv, char* column_1, char* column_2, char* column_3, char* column_4)
mesa formatting

2023-09-26 02:26 UTC, merged